
const Conditions = () => {
    return (
        <div className="container-fluid my-5 py-5">
            <div className="row pt-5 d-flex justify-content-center">
                <div className="col-md-10">
                    <div class="card p-5">
                        <div class="card-body">
                            <h4 className="text-center">TÉRMINOS Y CONDICIONES</h4>
                            <p>Este Documento</p>
                            <p>Bienvenido al sitio web www.vadevia.com y todas sus divisiones, subsidiarias, afiliadas y sitios de internet, la cual te ofrecen acceso al sitio web bajo los términos y condiciones establecidos en la misma, te rogamos que leas detenidamente los presentes términos y condiciones antes de utilizar el sitio web www.vadevia.com, ya que al entrar a nuestro sitio confirmas tu entendimiento con los mismos, si no aceptas estos términos y condiciones de uso, no podrás utilizar este sitio.</p>
                            <p>Los presentes términos y condiciones, regulan el uso del sitio web www.vadevia.com, del que AD TRIP HOLDING S.A.P.I DE C.V., es propietario, la cual es una Sociedad Anónima Promotora de Inversión de Capital Variable, con domicilio en Boulevard Adolfo Ruiz Cortines 3617, Piso 1, Col. Héroes de Padierna, Del. La Magdalena Contreras, C.P. 10700, Ciudad de México, México.</p>
                            <p>A través de su sitio web www.vadevia.com, AD TRIP HOLDING S.A.P.I DE C.V., pone a su disposición un ambiente digital en el cual concurren distintos tipos de usuarios, en el mismo, se ofertan alternativas de ciertos bienes o servicios; debido al contenido y la finalidad del sitio web, las personas que quieran beneficiarse de sus servicios deben de suscribirse, lo cual se realiza a través del llenado del formulario de registro y siguiendo los pasos que con posterioridad se les comunicará por medio de correo electrónico o en la plataforma para dichos efectos, la condición de suscriptor supone la aceptación de los términos y condiciones de uso.</p>
                            <p>Una vez completado el formulario de registro, el suscriptor del sitio recibirá un e-mail de confirmación, el suscriptor será el único responsable de confirmar su registro así como de mantener la contraseña proporcionada y así como otros identificadores de cuentas seguras, el titular de la cuenta es totalmente responsable de todas las actividades que ocurran bajo su contraseña o cuenta, por otra parte, debes notificarnos de cualquier uso no autorizado de tu contraseña o cuenta, de ninguna manera, nosotros seremos responsables, directos o indirectamente, por cualquier pérdida o daño de cualquier tipo incurridos como resultado de la falta de cumplimiento de esta condición.</p>
                            <p>AD TRIP HOLDING S.A.P.I DE C.V., se reserva el derecho de cambiar, modificar, añadir o eliminar partes de estos términos y condiciones de uso en cualquier momento, los cambios serán efectivos cuando se publiquen en el sitio www.vadevia.com, por favor revisa periódicamente las actualizaciones de estos términos y condiciones de uso, ya que tendrás que aceptar los cambios que se realicen para poder seguir accediendo al sitio y seguir comprando productos.</p>
                            <p>Estos términos se aplican independientemente de su estado durante el uso del sitio (s). Los términos y documentos relacionados detallan cómo tratamos cualquier información, datos, materiales, medios u otros elementos que usted proporcione al (los) sitio (s) (su "Contenido"). Lea detenidamente este documento antes de añadir cualquier contenido a su (s) sitio (s).</p>
                            <p>Uso de www.vadevia.com</p>
                            <p>Para poder utilizar el sitio www.vadevia.com debes de tener 18 años de edad o en su caso estar accediendo bajo la supervisión y consentimiento de tus padres, de quien detente el legar ejercicio de la patria potestad, guarda y custodia o bien de tutor legal si es el caso. Cada usuario sólo podrá ser titular de 1 (una) cuenta en el sitio www.vadevia.com, no pudiendo acceder a más de 1 (una) cuenta en el sitio web con distintas direcciones de correo electrónico o falseando, modificando y/o alterando sus datos personales de cualquier manera posible. Si se verificara o sospechara un uso fraudulento y/o malintencionado y/o contrario a estos Términos y Condiciones y/o contrarios a la buena fe, AD TRIP HOLDING S.A.P.I DE C.V. tendrá el derecho inapelable de dar por terminada la relación, dar de baja las cuentas y hasta colaborar judicialmente para la persecución a los infractores. Al aceptar los presentes términos y condiciones te concedemos una licencia no transferible y revocable para utilizar nuestro sitio, en virtud de los términos y condiciones descritos y aceptados, con el propósito de la compra de artículos ofertados en nuestra página.</p>
                            <p>El uso comercial o el nombre de terceros están prohibidos, salvo lo expresamente permitido por nosotros con anterioridad, cualquier infracción de estos términos y condiciones dará lugar a la revocación inmediata de la licencia otorgada en este apartado, sin previo aviso.</p>
                            <p>Ciertos servicios y las características relacionadas con los mismos, que pueden estar disponibles en el sitio www.vadevia.com, pueden requerir el registro o suscripción, si decides registrarte o suscribirte a cualquiera de estos servicios o funciones relacionadas, te comprometes a proporcionar información precisa y actualizada acerca de ti mismo, para actualizar rápidamente esa información si hay algún cambio.</p>
                            <p>Contenido / Infracción</p>
                            <p>AD TRIP HOLDING S.A.P.I DE C.V. y su sitio www.vadevia.com, y todas sus empresas afiliadas respetan la propiedad intelectual de terceros y pedimos a nuestros usuarios y socios de contenido que hagan lo mismo.</p>
                            <p>La publicación, reproducción, copia, distribución, modificación, exhibición pública o ejecución pública no autorizada de obras protegidas por derechos de autor constituyen una violación de los derechos del titular de los derechos de autor. Como condición para el uso de www.vadevia.com, usted acepta no utilizar ningún sitio de la plataforma para infringir los derechos de propiedad intelectual de terceros de ninguna manera. Terminaremos las cuentas de los Usuarios vadevia y bloquearemos el acceso a los Sitios vadevia de los Usuarios que sean infractores reincidentes de los derechos de autor u otros derechos de propiedad intelectual de terceros. Nos reservamos el derecho de tomar estas acciones en cualquier momento, a nuestra entera discreción, con o sin previo aviso, y sin ninguna responsabilidad para con el Usuario que está terminado o con el Usuario cuyo acceso está bloqueado. Si cree que su obra o marca registrada con derechos de autor ha sido cargada, enviada o copiada a vadevia y es accesible en vadevia de una manera que constituye una infracción de derechos de autor o marcas registradas, por favor proporcione una notificación debidamente constituida a hola@vadevia.com incluyendo la ubicación exacta de El contenido infractor, su base para reclamar la propiedad, su información de contacto completa y una captura de pantalla de la infracción reportada. Cualquier comunicación que recibamos no será confidencial o privilegiada de ninguna manera. Usted nos otorga una licencia mundial no exclusiva, transferible, sublicenciable, libre de regalías, y el derecho de usar el Contenido en nuestros sitios y usar, copiar, distribuir, enmendar y divulgar a terceros su Contenido como se describe en Estos términos y la Política de Privacidad de AD TRIP HOLDING S.A.P.I DE C.V.</p>
                            <p>Nuestra licencia para su contenido finaliza cuando elimina su contenido, excepto por su contenido que ha sido compartido con otros en el sitio y que no ha sido eliminado por los otros usuarios en cuestión. Las copias de su contenido pueden persistir durante algún tiempo después de eliminarlas debido al almacenamiento en caché, las copias de seguridad y otros aspectos técnicos del funcionamiento del sitio.</p>
                            <p>En el caso de que eliminemos su contenido, puede haber demoras en el almacenamiento en caché y puede haber copias del contenido alojadas en otros usuarios o sitios de terceros a los que no tenemos acceso ni control. La eliminación de su contenido no tiene efecto sobre el contenido que ha compartido con otros usuarios y que no ha sido eliminado por ellos.</p>
                            <p>Renuncias y limitación de responsabilidad</p>
                            <p>Este sitio y todos los contenidos del mismo se proporcionan "como están" y sin garantías de ningún tipo, ya sean expresas o implícitas, incluidas, pero no limitadas a, garantías de título o garantías implícitas de comerciabilidad o idoneidad para un propósito particular.</p>
                            <p>Usted reconoce, al usar este sitio, que el uso del mismo es bajo su propio riesgo, que asume la responsabilidad total por todos los costos asociados con todo el mantenimiento o reparaciones necesarias de cualquier equipo que use en relación con su uso del sitio, y que AD TRIP HOLDING S.A.P.I DE C.V. no será responsable por ningún daño de ningún tipo relacionado con su uso de este sitio.</p>
                            <p>AD TRIP HOLDING S.A.P.I DE C.V. no garantiza que el uso del sitio será ininterrumpido o libre de errores, ni garantiza la precisión, integridad o integridad de los materiales en este sitio, incluyendo, pero no limitado a, información de productos, precios y disponibilidad.</p>
                            <p>AD TRIP HOLDING S.A.P.I DE C.V. no será responsable por daños de ningún tipo que resulten del uso del sitio, incluidos, entre otros, daños directos, indirectos, incidentales, punitivos y consecuentes.</p>
                            <p>Algunos estados no permiten limitaciones en las garantías implícitas ni la exclusión o limitación de ciertos daños. Si estas leyes se aplican a usted, algunas o todas las renuncias, exclusiones o limitaciones anteriores pueden no aplicarse, y puede tener derechos adicionales.</p>
                            <p>Indemnización</p>
                            <p>Usted acepta defender, indemnizar y mantener indemne a AD TRIP HOLDING S.A.P.I DE C.V. de cualquier reclamo, daño, costo y gasto, incluidos los honorarios de abogados, que surjan de o estén relacionados con su uso del sitio.</p>
                            <p>Cesión</p>
                            <p>Usted no puede ceder ni transferir estos términos o sus derechos u obligaciones bajo estos términos en su totalidad o en parte sin el consentimiento previo por escrito de AD TRIP HOLDING S.A.P.I DE C.V. Cualquier intento de cesión o transferencia sin dicho consentimiento será nulo. AD TRIP HOLDING S.A.P.I DE C.V. puede ceder estos términos o cualquiera de sus derechos u obligaciones bajo estos términos sin su consentimiento.</p>
                            <p>Jurisdicción y Ley Aplicable</p>
                            <p>El uso de este sitio web y la compra de productos de este sitio se regirán e interpretarán de acuerdo con las leyes de los Estados Unidos Mexicanos. Cualquier disputa que surja en relación con estos términos se someterá a la jurisdicción exclusiva de los tribunales competentes de la Ciudad de México, México.</p>
                            <p>General</p>
                            <p>Estos términos y condiciones constituyen el acuerdo completo entre usted y AD TRIP HOLDING S.A.P.I DE C.V. con respecto al uso del sitio web y reemplazan cualquier acuerdo anterior entre usted y AD TRIP HOLDING S.A.P.I DE C.V. en relación con el uso del sitio web.</p>
                            <p>Si alguna disposición de estos términos y condiciones es considerada inválida por un tribunal competente, la invalidez de esa disposición no afectará la validez de las disposiciones restantes de estos términos y condiciones, que permanecerán en pleno vigor y efecto.</p>
                            <p>La falta de AD TRIP HOLDING S.A.P.I DE C.V. para insistir en el cumplimiento estricto de cualquiera de estos términos y condiciones no se interpretará como una renuncia a ninguno de sus derechos o disposiciones.</p>
                            <p>Contacto</p>
                            <p>Si tienes preguntas o inquietudes sobre estos términos y condiciones o el uso del sitio web, puedes ponerte en contacto con nosotros a través de hola@vadevia.com.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default Conditions
